### ISSUE TITLE
feat: 프로젝트 공고 페이징 기능 개발

### ISSUE THREAD

**Issue by yumzen** [Gongjakso/server#42]
## 💼 IssueName
> 프로젝트 공고 페이지 페이징 기능 개발

## 📝 Description
> 프로젝트 공고 페이지 전체/카테고리 페이징 기능 개발

## ❗️ Todo
> - [x] 전체 페이징 기능 개발
> - [x] 검색어 기반 페이지 기능 개발
> - [x] 기술 기반 페이지 기능 개발
> - [x] 최신순 정렬 기반 페이지 기능 개발 
> - [x] 지역 기반 페이지 기능 개발

**Comment by yumzen** [comment]
@dl-00-e8 
연휴동안 혼자 해결하지 못한 부분이 있어 도움 요청하고자 코멘트 남깁니다 ㅠ 시간되실 때 한번 확인해주시면 감사하겠습니다!!!
# 1. StackName 테이블 확인
프로젝트 공고를 stackname으로 조회할 수 있도록 stackName entity와 stackNameType enum을 생성해서 사진처럼 stackName 테이블이 만들어졌는데 1차적으로 이 테이블의 형태가 맞는 지에 대한 확인이 필요할 것 같습니다.
![image](https://github.com/Gongjakso/server/assets/109282927/e31f174d-07e3-47b1-8101-7c29779d5a8e).

# 2. StackName 기반 조회  쿼리문 확인
또, ec43a4a 참고해서 보시면, endpoint로 전달받은 stackName(ex.JAVA)이 stackName테이블의 stackNameType(ex.JAVA, SPRING, REACT)에 존재하면 해당 stackName에 대한 post를 불러오는 쿼리문을 작성했는데, 결과가 사진처럼 정상적으로 나오지 않아 테이블 생성에서 잘못 세팅 된 건지, 쿼리문이 잘못된 건지 확인이 필요할 것 같습니다.
![image](https://github.com/Gongjakso/server/assets/109282927/490f2527-8cb2-4430-ab1d-c0ad1b63ecee)

**Comment by dl-00-e8** [comment]
> @dl-00-e8 연휴동안 혼자 해결하지 못한 부분이 있어 도움 요청하고자 코멘트 남깁니다 ㅠ 시간되실 때 한번 확인해주시면 감사하겠습니다!!!
> 
> # 1. StackName 테이블 확인
> 프로젝트 공고를 stackname으로 조회할 수 있도록 stackName entity와 stackNameType enum을 생성해서 사진처럼 stackName 테이블이 만들어졌는데 1차적으로 이 테이블의 형태가 맞는 지에 대한 확인이 필요할 것 같습니다. ![image](https://private-user-images.githubusercontent.com/109282927/304036643-e31f174d-07e3-47b1-8101-7c29779d5a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDcwNDcsIm5iZiI6MTcwNzc0Njc0NywicGF0aCI6Ii8xMDkyODI5MjcvMzA0MDM2NjQzLWUzMWYxNzRkLTA3ZTMtNDdiMS04MTAxLTdjMjk3NzlkNWE4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYxNmEzMTQ4OTc0NzQ2ZDExZjkzYTEzYmVjMDRmZmU1MTQxYjc0YjNiNmZhMjg2NDk1Njg5N2JjNzE4M2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1p7OIjoyiz5yDyAC80VDixrDfCbMJuh3SsE6DuKbzw).
> 
> # 2. StackName 기반 조회 쿼리문 확인
> 또, [ec43a4a](https://github.com/Gongjakso/server/commit/ec43a4a8f24541bb90241b877acbe92cee555395) 참고해서 보시면, endpoint로 전달받은 stackName(ex.JAVA)이 stackName테이블의 stackNameType(ex.JAVA, SPRING, REACT)에 존재하면 해당 stackName에 대한 post를 불러오는 쿼리문을 작성했는데, 결과가 사진처럼 정상적으로 나오지 않아 테이블 생성에서 잘못 세팅 된 건지, 쿼리문이 잘못된 건지 확인이 필요할 것 같습니다. ![image](https://private-user-images.githubusercontent.com/109282927/304038787-490f2527-8cb2-4430-ab1d-c0ad1b63ecee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDcwNDcsIm5iZiI6MTcwNzc0Njc0NywicGF0aCI6Ii8xMDkyODI5MjcvMzA0MDM4Nzg3LTQ5MGYyNTI3LThjYjItNDQzMC1hYjFkLWMwYWQxYjYzZWNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmY0Y2E1NThhZGZmYTBhOTMzMDdmOTc0NTlhNjBhY2U5ZGQ5Nzc4NWY0YmRjODAxYWVmMjc2MzAyY2JlYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.piT_VeHQzSrOVAxEMHqJdcoi4-3VpCJX_y2m7tmTNlM)

일단 연휴기간 내내 너무 고생많으셨습니다!!
엄청난 고민 끝에 Query 어노테이션까지 사용해보셨네요! 정말정말 힘드셨을 것 같습니다. 
Query 어노테이션을 활용해서 지은님처럼 Pagination을 구축할 수 있어요! 다만 JPA의 장점을 활용하지는 못하게 되어, Query 어노테이션을 사용하지 않는 방식으로 저랑 시간 되면 리팩토링 한 번 진행해보면 좋을 것 같네요.

지은님이 작성해주신 방식 기반을 제 생각을 말씀드릴게요.
1. stackname을 엔티티로 만들고자 하는 접근 방식은 굉장히 좋다고 생각해요! 추가적으로 해당 스택으로 몇 명이 필요한지에 대한 정보까지 같이 들어가야 한다고 생각합니다. 그렇게 되면, 모집하고자 하는 직군의 수가 몇 명인지 조금 더 직관적일 수 있을 것 같아요. 
아니면 이 부분을 극단적으로 변경하는 방향성도 고민이 되긴 하는데, 변경은 프론트와 논의가 필요해서 후순위로 생각하고 있어요.
2. 검색 API가 정상적으로 조회되지 않는 경우는 크게 3가지가 있을 것 같아요.
(1) DB에 값이 정상적으로 들어가 있지 않았거나 (우리가 목표로 하는 데이터가)
(2) Query 어노테이션에 작성하신 쿼리 내에서 where 조건문에 문제가 있거나 (where 조건을 하나씩 빼보시면서 확인해야함)
(3) searchKeyWork가 null값으로 전송되고 있어서 (like 문에서 Null이 정상적으로 무시되지 않는 경우)
위 3가지 경우라고 생각을 합니다!
그래서 이 3가지로 한 번 확인해보시고, 안 된다면 저랑 다시 한 번 리뷰 진행해보면 좋을 것 같아요!

**Comment by yumzen** [comment]
> > @dl-00-e8 연휴동안 혼자 해결하지 못한 부분이 있어 도움 요청하고자 코멘트 남깁니다 ㅠ 시간되실 때 한번 확인해주시면 감사하겠습니다!!!
> > # 1. StackName 테이블 확인
> > 프로젝트 공고를 stackname으로 조회할 수 있도록 stackName entity와 stackNameType enum을 생성해서 사진처럼 stackName 테이블이 만들어졌는데 1차적으로 이 테이블의 형태가 맞는 지에 대한 확인이 필요할 것 같습니다. ![image](https://private-user-images.githubusercontent.com/109282927/304036643-e31f174d-07e3-47b1-8101-7c29779d5a8e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDcwNDcsIm5iZiI6MTcwNzc0Njc0NywicGF0aCI6Ii8xMDkyODI5MjcvMzA0MDM2NjQzLWUzMWYxNzRkLTA3ZTMtNDdiMS04MTAxLTdjMjk3NzlkNWE4ZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT00ZDYxNmEzMTQ4OTc0NzQ2ZDExZjkzYTEzYmVjMDRmZmU1MTQxYjc0YjNiNmZhMjg2NDk1Njg5N2JjNzE4M2Y2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.j1p7OIjoyiz5yDyAC80VDixrDfCbMJuh3SsE6DuKbzw).
> > # 2. StackName 기반 조회 쿼리문 확인
> > 또, [ec43a4a](https://github.com/Gongjakso/server/commit/ec43a4a8f24541bb90241b877acbe92cee555395) 참고해서 보시면, endpoint로 전달받은 stackName(ex.JAVA)이 stackName테이블의 stackNameType(ex.JAVA, SPRING, REACT)에 존재하면 해당 stackName에 대한 post를 불러오는 쿼리문을 작성했는데, 결과가 사진처럼 정상적으로 나오지 않아 테이블 생성에서 잘못 세팅 된 건지, 쿼리문이 잘못된 건지 확인이 필요할 것 같습니다. ![image](https://private-user-images.githubusercontent.com/109282927/304038787-490f2527-8cb2-4430-ab1d-c0ad1b63ecee.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDc3NDcwNDcsIm5iZiI6MTcwNzc0Njc0NywicGF0aCI6Ii8xMDkyODI5MjcvMzA0MDM4Nzg3LTQ5MGYyNTI3LThjYjItNDQzMC1hYjFkLWMwYWQxYjYzZWNlZS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMjEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDIxMlQxNDA1NDdaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1kZmY0Y2E1NThhZGZmYTBhOTMzMDdmOTc0NTlhNjBhY2U5ZGQ5Nzc4NWY0YmRjODAxYWVmMjc2MzAyY2JlYjQ2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.piT_VeHQzSrOVAxEMHqJdcoi4-3VpCJX_y2m7tmTNlM)
> 
> 일단 연휴기간 내내 너무 고생많으셨습니다!! 엄청난 고민 끝에 Query 어노테이션까지 사용해보셨네요! 정말정말 힘드셨을 것 같습니다. Query 어노테이션을 활용해서 지은님처럼 Pagination을 구축할 수 있어요! 다만 JPA의 장점을 활용하지는 못하게 되어, Query 어노테이션을 사용하지 않는 방식으로 저랑 시간 되면 리팩토링 한 번 진행해보면 좋을 것 같네요.
> 
> 지은님이 작성해주신 방식 기반을 제 생각을 말씀드릴게요.
> 
> 1. stackname을 엔티티로 만들고자 하는 접근 방식은 굉장히 좋다고 생각해요! 추가적으로 해당 스택으로 몇 명이 필요한지에 대한 정보까지 같이 들어가야 한다고 생각합니다. 그렇게 되면, 모집하고자 하는 직군의 수가 몇 명인지 조금 더 직관적일 수 있을 것 같아요.
>    아니면 이 부분을 극단적으로 변경하는 방향성도 고민이 되긴 하는데, 변경은 프론트와 논의가 필요해서 후순위로 생각하고 있어요.
> 2. 검색 API가 정상적으로 조회되지 않는 경우는 크게 3가지가 있을 것 같아요.
>    (1) DB에 값이 정상적으로 들어가 있지 않았거나 (우리가 목표로 하는 데이터가)
>    (2) Query 어노테이션에 작성하신 쿼리 내에서 where 조건문에 문제가 있거나 (where 조건을 하나씩 빼보시면서 확인해야함)
>    (3) searchKeyWork가 null값으로 전송되고 있어서 (like 문에서 Null이 정상적으로 무시되지 않는 경우)
>    위 3가지 경우라고 생각을 합니다!
>    그래서 이 3가지로 한 번 확인해보시고, 안 된다면 저랑 다시 한 번 리뷰 진행해보면 좋을 것 같아요!

말씀해주신 3가지 위주로 한번 더 확인해보고 안 되면 다시 말씀드리겠습니다!! 감사합니다 :)

**Comment by dl-00-e8** [comment]
추가적으로 Query 어노테이션을 사용하지 않는 방향으로는 아래와 같은 방식이 될 거 같아요!
`Page<Post> findAllByTitleContainsAndDeletedAtIsNullAndEndDateAfterAndStatusIs(String title, LocalDateTime endDate, PostType status);`

관련 레퍼런스 링크 몇 개 드릴게요! (아마 보셨을 거 같지만..)
- https://velog.io/@kimdy0915/JPA-Spring-Data-Jpa-Pageable%EB%A1%9C-Pagination-%EC%89%BD%EA%B2%8C-%EA%B5%AC%ED%98%84%ED%95%98%EA%B8%B0#2-%EB%82%B4%EA%B0%80-%EC%93%B4-%EB%A6%AC%EB%B7%B0-%EC%A1%B0%ED%9A%8C-%ED%8E%98%EC%9D%B4%EC%A7%80%EB%84%A4%EC%9D%B4%EC%85%98
- https://colour-my-memories-blue.tistory.com/10
